spool LOG_portal_drop_users_cascade_ora.txt;

-- Tesco Bank PCU Oracle Database Scripts.
--------------------------------------------------------

-- V1 May 2015

-- DROP APPLICATION ROLES --

-- DROP HUMAN DB ROLES --

-- DROP DATABASE ROLES --

-- DROP USERS AND ALL OWNED OBJECTS
DROP USER "PCAO" CASCADE;
DROP USER "TBCWP_SSS" CASCADE;

-- WARNING - DROP TABLESPACE - ONLY IN DEVELOPMENT SERVERS --
DROP TABLESPACE "PORTAL_INDEX" INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE "PORTAL_DATA" INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE "SSS_INDEX" INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE "SSS_DATA" INCLUDING CONTENTS AND DATAFILES;

spool off;
