spool LOG_portal_create_objects_portal_ora.txt;

-- Tesco Bank PCU Oracle Database Scripts.
--------------------------------------------------------

-- V1 May 2015

-- SEQUENCES
-- TABLES
-- INDEXES
-- VIEWS
-- PACKAGES
-- TRIGGERS


--- START SCRIPT ---

--------------------------------------------------------
--  DDL for Sequence PCAO_APPLICATION_ID_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "PCAO"."PCAO_APPLICATION_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 41 CACHE 20 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table PCAO_APPLICATION
--------------------------------------------------------

  CREATE TABLE "PCAO"."PCAO_APPLICATION" 
   (	"ID" NUMBER(*,10), 
	"APPLICATION_ID" VARCHAR2(10 BYTE), 
	"RESUME_APPLICATION_STAGE" VARCHAR2(50 BYTE), 
	"FURTHEST_APPLICATION_STAGE" VARCHAR2(50 BYTE), 
	"PA_OVERDRAFT_ELIGIBILITY" NUMBER(1,0), 
	"JA_FIRST_NAME" VARCHAR2(20 BYTE), 
	"JA_SURNAME" VARCHAR2(20 BYTE), 
	"JA_CIF" VARCHAR2(10 BYTE), 
	"JA_OVERDRAFT_ELIGIBILITY" NUMBER(1,0), 
	"TB_ID" VARCHAR2(150 BYTE), 
	"PASSWORD" VARCHAR2(150 BYTE), 
	"FAILED_PASSWORD_ATTEMPTS" NUMBER(1,0), 
	"CREATED_ON" TIMESTAMP (6), 
	"LAST_MODIFIED" TIMESTAMP (6), 
	"PROMO_CODE" VARCHAR2(10 CHAR), 
	"SWITCHING_OPTION" VARCHAR2(25 BYTE), 
	"PA_SWITCHING_POSSIBLE_STATUS" VARCHAR2(30 BYTE), 
	"JA_SWITCHING_POSSIBLE_STATUS" VARCHAR2(30 BYTE), 
	"PA_HAS_PREV_MOTHERS_MDN_NAME" NUMBER(1,0) DEFAULT 0, 
	"JA_HAS_PREV_MOTHERS_MDN_NAME" NUMBER(1,0), 
	"SWITCHING_TYPE" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAL_DATA" ;

   COMMENT ON COLUMN "PCAO"."PCAO_APPLICATION"."PA_HAS_PREV_MOTHERS_MDN_NAME" IS '1 if primary applicant has previously entered mothers maiden name, 0 otherwise';
   COMMENT ON COLUMN "PCAO"."PCAO_APPLICATION"."JA_HAS_PREV_MOTHERS_MDN_NAME" IS '1 if joint applicant has previously entered mothers maiden name, 0 otherwise';
--------------------------------------------------------
--  DDL for Index PCAO_APPLICATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PCAO"."PCAO_APPLICATION_PK" ON "PCAO"."PCAO_APPLICATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAL_INDEX" ;
--------------------------------------------------------
--  DDL for Index PCAO_APPLICATION_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PCAO"."PCAO_APPLICATION_UK1" ON "PCAO"."PCAO_APPLICATION" ("APPLICATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAL_INDEX" ;
--------------------------------------------------------
--  Constraints for Table PCAO_APPLICATION
--------------------------------------------------------

  ALTER TABLE "PCAO"."PCAO_APPLICATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PCAO"."PCAO_APPLICATION" MODIFY ("APPLICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "PCAO"."PCAO_APPLICATION" MODIFY ("RESUME_APPLICATION_STAGE" NOT NULL ENABLE);
  ALTER TABLE "PCAO"."PCAO_APPLICATION" MODIFY ("FURTHEST_APPLICATION_STAGE" NOT NULL ENABLE);
  ALTER TABLE "PCAO"."PCAO_APPLICATION" MODIFY ("FAILED_PASSWORD_ATTEMPTS" NOT NULL ENABLE);
  ALTER TABLE "PCAO"."PCAO_APPLICATION" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "PCAO"."PCAO_APPLICATION" MODIFY ("LAST_MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "PCAO"."PCAO_APPLICATION" ADD CONSTRAINT "PCAO_APPLICATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAL_INDEX"  ENABLE;
  ALTER TABLE "PCAO"."PCAO_APPLICATION" ADD CONSTRAINT "PCAO_APPLICATION_UK1" UNIQUE ("APPLICATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PORTAL_INDEX"  ENABLE;
  ALTER TABLE "PCAO"."PCAO_APPLICATION" MODIFY ("SWITCHING_OPTION" NOT NULL ENABLE);
  ALTER TABLE "PCAO"."PCAO_APPLICATION" MODIFY ("PA_HAS_PREV_MOTHERS_MDN_NAME" NOT NULL ENABLE);
spool off;
