---
# vars file for java

# General
tmp: /tmp
app_home: /opt/jboss

# User variables 
java_home: "/opt/jboss/java"
java_user: jboss
java_group: jboss

# Download variables
java_download_prefix: "http://download.oracle.com/otn-pub/java/jdk/"
jdk_package: "jdk-7u51-linux-x64.tar.gz"
jdk_package_prefix: "7u51-b13"
jdk_folder: "jdk1.7.0_51"

