---
- name: Install python-ssl
  yum: name=python-ssl state=present
  when: ansible_distribution_major_version == "5"
  tags:  jboss_eap_install

- name: Add the jboss group 
  group: name=jboss state=present
  tags:  jboss_eap_install

- name: Add the jboss user 
  user:  name=jboss shell=/bin/bash createhome=yes group=jboss
  tags:  jboss_eap_install

- name: Creating directories
  file: path={{ item }} state=directory owner=jboss group=jboss mode=755
  with_items:
     - "{{ jboss_root }}"
     - "{{ broker_config }}"
     - "{{ broker_scripts }}"
  tags:  jboss_eap_install

- name: Install Python26 Boto libraries 
  yum: name=python26-boto state=latest
  when: ansible_distribution_major_version == "5"
  tags: jboss_eap_install

- name: Python 2.6
  set_fact: 
    ansible_python_interpreter: /usr/bin/python2.6
  tags:  jboss_eap_install
  
- name:  Pull JBoss EAP from Nexus
  get_url: url=http://yumuser:T35c0Bank@nexus.tbdevops.com/nexus/content/repositories/vendor-licenced/org/jboss/3.0.zip/jboss-3.0.zip.zip dest=/opt/jboss/{{ eap_package }}
  tags: jboss_eap_install

- name: Python 2.4
  set_fact: 
    ansible_python_interpreter: /usr/bin/python2
  tags:  jboss_eap_install

- name: Unzip EAP package
  unarchive: src={{ jboss_root }}/{{ eap_package }} dest={{ jboss_root }} copy=no
  tags:
    - jboss_eap_install

- name: Remove EAP package
  file: path=/{{ jboss_root }}/{{ eap_package }} state=absent 
  tags: jboss_eap_install

- name: Symlink EAP package
  file:  path='{{ jboss_root }}/jbosseap' src={{ eap_major_version }} state=link
  tags:  jboss_eap_install

- name: Change file permissions
  file: path={{ jboss_root }} owner=jboss group=jboss recurse=yes
  tags:  jboss_eap_install

- name: Set the JBoss profile 
  template: src=../templates/bash_profile.j2 dest=/home/jboss/.bash_profile 
  tags: jboss_eap_install

- name: Set the JBoss bashrc 
  template: src=../templates/bashrc.j2 dest=/home/jboss/.bashrc
  tags: jboss_eap_install

- name: Install the JBoss service configuration 
  template: src=jboss-as.conf.j2 dest={{ broker_config }}/jboss-as.conf
  tags: jboss_eap_install

- name: Install the JBoss service script
  template: src=jboss-as-standalone.sh.j2 dest=/etc/init.d/jboss 
  tags: jboss_eap_install

- name: Set JBoss service script permissions
  file: path=/etc/init.d/jboss mode=0755
  tags: jboss_eap_install

- name: Increase file open security limits
  lineinfile: dest=/etc/security/limits.conf line="{{ item.line }}"
  with_items:
    - { line: 'jboss          hard    nofile          16384'}
    - { line: 'jboss          soft    nofile          16384'}
  tags:  increase_file_open_security_limits
