ansible_python_interpreter: /usr/bin/python
ntp_server: 0.uk.pool.ntp.org

epel5_url: http://dl.fedoraproject.org/pub/epel/5/x86_64/epel-release-5-4.noarch.rpm
epel5_package: epel-release-5*.rpm

epel6_url: http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
epel6_package: epel-release-6*.rpm

ssh_users: 
  - name: u007614 
    key: "{{ lookup ('file', 'fpringle.pub') }}"
