Vagrant.configure(2) do |config|
  config.vm.box = "chef/centos-5.11"
  config.vm.define "pcu"
  config.vm.hostname = "pcu"
  config.vm.network "forwarded_port", guest: 80, host:8080
  config.vm.network "forwarded_port", guest: 8080, host:9090
  config.vm.network "forwarded_port", guest: 8181, host:8181
  config.vm.network "forwarded_port", guest: 1521, host:1521
  config.vm.network "forwarded_port", guest: 8787, host:8787
  config.vm.provider "virtualbox" do |v|
    v.memory = 6144
    v.cpus = 2
  end
  #config.vm.provision "shell", inline: "yum -y update"
  config.vm.provision "shell", inline: "yum -y install python-simplejson"
  config.vm.provision "shell", inline: "yum -y install bc"
  config.vm.provision "shell", inline: "yum -y install unzip"
  config.vm.provision "shell", inline: "yum -y install binutils compat-libstdc++-33 elfutils-libelf elfutils-libelf-devel glibc glibc-common glibc-devel gcc gcc-c++ libaio libaio-devel libgcc libstdc++ libstdc++-devel make sysstat unixODBC unixODBC-devel pdksh"
  config.vm.provision :shell, path: "increase_swap.sh"
  config.vm.provision "shell", inline: "iptables -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT"
  config.vm.provision "shell", inline: "service iptables save"
  config.vm.provision "shell", inline: "service iptables start"
  config.vm.provision "shell", inline: "sudo cp -r /home/vagrant/.ssh /root/"
#  config.vm.provision :ansible do |ansible|
#	  ansible.playbook = "pcu_dev.yml"
#	  ansible.groups = {
#		"pcu_devservers" => ["pcu"]
#		}
#	  ansible.sudo = true
 # end
end

